PlanSuite/Controllers/JoinController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PlanSuite.Data;
using PlanSuite.Enums;
using PlanSuite.Models.Persistent;
using PlanSuite.Models.Temporary;
using PlanSuite.Services;
using PlanSuite.Utility;
using Stripe;
using Stripe.Checkout;
using static PlanSuite.Models.Temporary.CreateOrganisationRegistrationModel;

namespace PlanSuite.Controllers
{
    public class JoinController : Controller
    {
        private readonly UserManager<ApplicationUser> m_UserManager;
        private readonly SignInManager<ApplicationUser> m_SignInManager;
        private readonly ApplicationDbContext m_Database;
        private readonly ILogger<JoinController> m_Logger;
        private readonly IUserStore<ApplicationUser> m_UserStore;
        private readonly IUserEmailStore<ApplicationUser> m_EmailStore;
        private readonly ProjectService m_ProjectService;
        private readonly OrganisationService m_OrganisationService;

        public JoinController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext database, ILogger<JoinController> logger, IUserStore<ApplicationUser> userStore, ProjectService projectService, OrganisationService organisationService)
        {
            m_UserManager = userManager;
            m_SignInManager = signInManager;
            m_Database = database;
            m_Logger = logger;
            m_UserStore = userStore;
            m_EmailStore = GetEmailStore();
            m_ProjectService = projectService;
            m_OrganisationService = organisationService;
        }

        [Route("welcome")]
        public async Task<IActionResult> Welcome()
        {
            WelcomePageModel model = new WelcomePageModel();
            if(!m_SignInManager.IsSignedIn(User))
            {
                // Redirect the user to the sign in page.
                return Redirect("/Identity/Account/Login");
            }

            var user = await m_UserManager.GetUserAsync(User);
            if(user == null)
            {
                // User has returned null, this should never happen in 99.9% of cases.
                return NotFound("User returned null, this should not happen.");
            }

            m_Logger.LogInformation($"Showing first time login page for {user.FullName}");
            if (user.FinishedFirstTimeLogin == true)
            {
                // User has already completed their first time login, so we're just gonna redirect them to the index page.
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [Route("upgrade")]
        public async Task<IActionResult> Upgrade()
        {
            WelcomePageModel model = new WelcomePageModel();
            if (!m_SignInManager.IsSignedIn(User))
            {
                // Redirect the user to the sign in page.
                return Redirect("/Identity/Account/Login");
            }

            var user = await m_UserManager.GetUserAsync(User);
            if (user == null)
            {
                // User has returned null, this should never happen in 99.9% of cases.
                return NotFound("User returned null, this should not happen.");
            }

            return View(model);
        }

        public async Task<IActionResult> ContinueWithFree()
        {
            if (!m_SignInManager.IsSignedIn(User))
            {
                // Redirect the user to the sign in page.
                return Redirect("/Identity/Account/Login");
            }

            var user = await m_UserManager.GetUserAsync(User);
            if (user == null)
            {
                // User has returned null, this should never happen.
                return NotFound("User returned null, this should not happen.");
            }

            if (user.FinishedFirstTimeLogin == true)
            {
                // User has already completed their first time login, so we're just gonna redirect them to the index page.
                return RedirectToAction("Index", "Home");
            }

            m_Logger.LogInformation($"Setting free tier for {user.FullName}");
            user.PaymentTier = PaymentTier.Free;
            user.FinishedFirstTimeLogin = true;
            await m_UserManager.UpdateAsync(user);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> UpgradePlan()
        {
            if (!m_SignInManager.IsSignedIn(User))
            {
                // Redirect the user to the sign in page.
                return Redirect("/Identity/Account/Login");
            }

            var user = await m_UserManager.GetUserAsync(User);
            if (user == null)
            {
                // User has returned null, this should never happen.
                return NotFound("User returned null, this should not happen.");
            }

            var customerService = new CustomerService();
            Customer customer = await CreateUserStripeCustomer(user, customerService);

            customer = await customerService.GetAsync(user.StripeCustomerId);
            if (customer == null)
            {
                customer = await PaymentUtils.CreateCustomerAsync(user);

                user.StripeCustomerId = customer.Id;
                await m_UserManager.UpdateAsync(user);
            }

            string domain = $"https://{HttpContext.Request.Host}";
            string lookupKey = Request.Form["lookup_key"];
            m_Logger.LogInformation($"Domain is {domain}");

            PaymentTier paymentTier = PaymentTier.Plus;
            if (lookupKey == PaymentService.ProUrl)
            {
                paymentTier = PaymentTier.Pro;
            }

            // Create sale object
            Sale sale = new Sale
            {
                SaleDate = DateTime.Now,
                OwnerId = Guid.Parse(user.Id),
                PaymentTier = paymentTier,
                SaleState = SaleState.Pending
            };

            await m_Database.Sales.AddAsync(sale);
            await m_Database.SaveChangesAsync();

            m_Logger.LogInformation($"Create prices");
            var priceOptions = new PriceListOptions
            {
                LookupKeys = new List<string>
                {
                    lookupKey
                }
            };

            var priceService = new PriceService();
            StripeList<Price> prices = priceService.List(priceOptions);

            m_Logger.LogInformation($"Create session options {prices.Data.Count}");
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        Price = lookupKey,
                        Quantity = 1
                    }
                },
                Mode = "subscription",
                SuccessUrl = domain + "/api/Payment/Success?sessionId={CHECKOUT_SESSION_ID}",
                CancelUrl = domain + "/api/Payment/Cancel",
                AutomaticTax = new SessionAutomaticTaxOptions { Enabled = true },
                ClientReferenceId = sale.Id.ToString()
            };

            m_Logger.LogInformation("Create session");
            var service = new SessionService();
            Session session = service.Create(options);

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        private async Task<Customer> CreateUserStripeCustomer(ApplicationUser user, CustomerService customerService)
        {
            Customer customer;
            if (string.IsNullOrEmpty(user.StripeCustomerId))
            {
                m_Logger.LogInformation($"Creating stripe customer for user {user.Id}");
                customer = await PaymentUtils.CreateCustomerAsync(user);

                Console.WriteLine(customer.ToJson());

                user.StripeCustomerId = customer.Id;
                await m_UserManager.UpdateAsync(user);
            }
            else
            {
                customer = await customerService.GetAsync(user.StripeCustomerId);
                if (customer == null)
                {
                    customer = await PaymentUtils.CreateCustomerAsync(user);

                    Console.WriteLine(customer.ToJson());

                    user.StripeCustomerId = customer.Id;
                    await m_UserManager.UpdateAsync(user);
                }
            }

            return customer;
        }

        [Route("upgraded/{saleId}&{amount}")]
        public IActionResult UpgradeSuccess(int saleId, long amount)
        {
            UpgradeSuccessModel model = new UpgradeSuccessModel();

            var sale = m_Database.Sales.Where(s => s.Id == saleId).FirstOrDefault();
            if (sale == null)
            {
                m_Logger.LogWarning($"No sale for saleId {saleId} found.");
                return Redirect("/Home/Index");
            }

            model.Sale = sale;
            model.Amount = (int)amount;

            return View(model);
        }

        public async Task<IActionResult> ContinueRegistration(FinishRegistrationModel.FinishRegistrationInputModel input)
        {
            Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(input));
            if(!ModelState.IsValid)
            {
                return BadRequest("ModelState invalid");
            }

            ApplicationUser user = await m_UserManager.FindByIdAsync(input.UserId.ToString());
            if(user == null)
            {
                return BadRequest("User was null during registration");
            }

            bool hasPassword = await m_UserManager.HasPasswordAsync(user);
            if (hasPassword == false)
            {

PlanSuite/Views/Join/CreateOrganisation.cshtml
@using PlanSuite.Enums
@model PlanSuite.Models.Temporary.CreateOrganisationRegistrationModel
@{
    ViewData["Title"] = "Create Organisation";
}

<div class="container register-div">
    <div class="ps-alert ps-alert-error d-none" id="error"></div>
    @using (Html.BeginForm("CreateOrganisationRegistration", "Join", FormMethod.Post))
    {
        @Html.ValidationMessageFor(model => model.Input, "", new { @class="text-danger" })
        <input type="hidden" asp-for="Input.UserId" value="@Model.UserId" />
        <h1 class="register-header text-center">Let's get you up and running!</h1>
        <p class="register-subheading-2">Tell us more information about your organisation.</p>
        <p class="register-subheading-3">What is your organisations name?</p>
        <div class="mb-3">
            @Html.EditorFor(model => model.Input.OrganisationName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Input.OrganisationName, "", new { @class = "text-danger" })
        </div>
        <p class="register-subheading-3">What is your primary industry?</p>
        <div class="mb-3">
            <select class="form-select" asp-for="Input.Industry" asp-items="Html.GetEnumSelectList<Industry>()">
                <option selected>Select industry...</option>
            </select>
            @Html.ValidationMessageFor(model => model.Input.Industry, "", new { @class = "text-danger" })
        </div>
        <p class="register-subheading-3">Give us a small brief about your organisation?</p>
        <div class="mb-3">
            @Html.TextAreaFor(model => model.Input.Description, 3, 3, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Input.Description, "", new { @class = "text-danger" })
        </div>
        <button type="submit" id="continueBtn" class="btn ps-btn-primary">Finish</button>
    }
</div>

PlanSuite/Views/Join/FinishRegistration.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PlanSuite.Models.Temporary.FinishRegistrationModel
@{
    ViewData["Title"] = "Welcome to Plan Suite";
}

<div class="container register-div">
    <div class="ps-alert ps-alert-error d-none" id="error"></div>
    @using (Html.BeginForm("ContinueRegistration", "Join", FormMethod.Post))
    {
        @Html.ValidationMessageFor(model => model.Input, "", new { @class="text-danger" })
        <input type="hidden" asp-for="Input.UserId" value="@Model.UserId" />
        <div id="part_1">
            <h1 class="register-header text-center">Welcome to Plan Suite!</h1>
            <p class="register-subheading-2">You're signing up as @Model.Email<text>.</text></p>
            <p class="register-subheading-3">What is your full name?</p>
            <div class="row">
                <div class="mb-3 col-md">
                    @Html.LabelFor(model => model.Input.FirstName, new { htmlAttributes = new { @class = "form-label" } })
                    @Html.EditorFor(model => model.Input.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Input.FirstName, "", new { @class = "text-danger" })
                </div>
                <div class="mb-3 col-md">
                    @Html.LabelFor(model => model.Input.LastName, new { htmlAttributes = new { @class = "form-label" } })
                    @Html.EditorFor(model => model.Input.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Input.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
            <button type="button" id="continueBtn" class="btn ps-btn-primary">Continue</button>
        </div>
        <div class="d-none" id="part_2">
            <p class="register-subheading-3">What password would you like to use?</p>
            <div class="mb-3">
                @Html.LabelFor(model => model.Input.Password, new { htmlAttributes = new { @class = "form-label" } })
                @Html.EditorFor(model => model.Input.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Input.Password, "", new { @class = "text-danger" })
            </div>
            <div class="mb-3">
                @Html.LabelFor(model => model.Input.ConfirmPassword, new { htmlAttributes = new { @class = "form-label" } })
                @Html.EditorFor(model => model.Input.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Input.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
            <div class="mb-3">
                <button type="button" id="backBtn" class="btn ps-btn-secondary">Go Back</button>
                <button type="submit" class="btn ps-btn-primary">Let's go!</button>
            </div>
        </div>
    }
</div>

@section Scripts {
    <script type="module" src="~/js/login/finishRegistration.js" asp-append-version="true"></script>
}

PlanSuite/Views/Join/Upgrade.cshtml
@using Microsoft.AspNetCore.Identity
@using PlanSuite.Enums
@using PlanSuite.Models.Persistent
@model PlanSuite.Models.Temporary.WelcomePageModel
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@{
    ViewData["Title"] = "Upgrade";
    ApplicationUser user = await UserManager.GetUserAsync(User);
}

<script src="https://js.stripe.com/v3/"></script>

<div class="container py-3">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="text-center">Thinking about upgrading?</h1>
        <h4>We're glad you're considering upgrading. Here are the plans we offer below.</h4>
        <h5>Select your plan to continue your upgrade.</h5>
    </div>

    <div class="row row-cols-1 row-cols-md-2 mb-3 text-center">
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm pricing-card">
                <div class="card-header py-3" style="background-color: var(--blue-1);">
                    <h4 class="my-0 fw-normal text-light">Plus</h4>
                    <span class="badge bg-warning text-dark fs-6 mt-2">Best Value</span>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">£4.99<span class="text-muted fw-light">/mo</span></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <partial name="Pricing/_Plus"/>
                    </ul>
                </div>
                <div class="card-footer">
                    <form method="post" asp-controller="Join" asp-action="UpgradePlan">
                        <input type="hidden" name="lookup_key" value="price_1LSNmSJVn9VR77kgkVMJa6PW" />
                        <button id="btnUpgradePlus" type="submit" class="w-100 btn btn-lg ps-btn-primary"><i class="bi bi-arrow-up-circle"></i> Upgrade to Plus</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm pricing-card">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Pro</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">£8.99<span class="text-muted fw-light">/mo</span></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <partial name="Pricing/_Pro"/>
                    </ul>
                </div>
                <div class="card-footer">
                    <a class="w-100 btn btn-lg ps-btn-secondary" asp-controller="Join" asp-action="UpgradePlan" asp-route-tier="@((int)PaymentTier.Pro)"><i class="bi bi-arrow-up-circle"></i> Upgrade to Pro</a>
                </div>
            </div>
        </div>
    </div>
</div>

PlanSuite/Views/Join/UpgradePlan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PlanSuite/Views/Join/UpgradeSuccess.cshtml
@using PlanSuite.Controllers.Api
@using System.Web
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PlanSuite.Models.Temporary.UpgradeSuccessModel
@{
}

<div class="container py-3">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="text-center">Thanks for upgrading!</h1>
    </div>

    <div class="mb-3 text-center">
        <p>Your upgrade has been confirmed and processed. You will recieve a receipt (also shown below) via email shortly. You can start using PlanSuite with all the @Model.Sale.PaymentTier features you expect.</p>

        <div style="background-color: #FFF; color: #000; min-height: 1rem; min-width:100%; border: solid black; padding:0.5rem;" class="mb-3 text-start">@Html.Raw(PaymentController.GetPaymentReceiptString(Model.Sale, Model.Amount))</div>

        <a class="btn ps-btn-primary" href="~/Home/Index"><i class="bi bi-arrow-right-circle"></i> Continue to PlanSuite</a>
    </div>
</div>

PlanSuite/Views/Join/Welcome.cshtml
@using PlanSuite.Enums
@model PlanSuite.Models.Temporary.WelcomePageModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Welcome";
}

<script src="https://js.stripe.com/v3/"></script>

<div class="container py-3">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="text-center">Welcome to PlanSuite</h1>
        <h4>We're glad you've chosen to join us. Here are the plans we offer below.</h4>
        <h5>Select your plan.</h5>
    </div>

    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm pricing-card">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Free</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">£0<span class="text-muted fw-light">/mo</span></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <partial name="Pricing/_Free"/>
                    </ul>
                </div>
                <div class="card-footer">
                    <a class="w-100 btn btn-lg ps-btn-secondary" asp-controller="Join" asp-action="ContinueWithFree"><i class="bi bi-arrow-right-circle"></i> Continue for free</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm pricing-card">
                <div class="card-header py-3" style="background-color: var(--blue-1);">
                    <h4 class="my-0 fw-normal text-light">Plus</h4>
                    <span class="badge bg-warning text-dark fs-6 mt-2">Best Value</span>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">£4.99<span class="text-muted fw-light">/mo</span></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <partial name="Pricing/_Plus"/>
                    </ul>
                </div>
                <div class="card-footer">
                    <form method="post" asp-controller="Join" asp-action="UpgradePlan">
                        <input type="hidden" name="lookup_key" value="price_1LSNmSJVn9VR77kgkVMJa6PW" />
                        <button id="btnUpgradePlus" type="submit" class="w-100 btn btn-lg ps-btn-primary"><i class="bi bi-arrow-up-circle"></i> Upgrade to Plus</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm pricing-card">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Pro</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">£8.99<span class="text-muted fw-light">/mo</span></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <partial name="Pricing/_Pro"/>
                    </ul>
                </div>
                <div class="card-footer">
                    <a class="w-100 btn btn-lg ps-btn-secondary" asp-controller="Join" asp-action="UpgradePlan" asp-route-tier="@((int)PaymentTier.Pro)"><i class="bi bi-arrow-up-circle"></i> Upgrade to Pro</a>
                </div>
            </div>
        </div>
    </div>
</div>