PlanSuite/Controllers/JournalController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlanSuite.Data;
using PlanSuite.Interfaces;
using PlanSuite.Models.Persistent;
using PlanSuite.Models.Temporary;
using PlanSuite.Services;
using PlanSuite.Utility;

namespace PlanSuite.Controllers
{
    public class JournalController : Controller
    {
        private readonly ApplicationDbContext m_Database;
        private readonly ILogger<HomeController> m_Logger;
        private readonly SignInManager<ApplicationUser> m_SignInManager;
        private readonly UserManager<ApplicationUser> m_UserManager;
        private readonly LocalisationService m_Localisation;
        private readonly AuditService m_AuditService;
        private readonly IWebHostEnvironment m_Environment;
        private readonly IPathService m_PathService;

        public JournalController(ApplicationDbContext context, ILogger<HomeController> logger, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, AuditService auditService, IWebHostEnvironment environment, IPathService pathService)
        {
            m_Database = context;
            m_Logger = logger;
            m_UserManager = userManager;
            m_SignInManager = signInManager;
            m_Localisation = LocalisationService.Instance;
            m_AuditService = auditService;
            m_Environment = environment;
            m_PathService = pathService;
        }

        [Route("journal/list")]
        public async Task<IActionResult> Index()
        {
            if(!m_SignInManager.IsSignedIn(User))
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            CommonCookies.ApplyCommonCookies(HttpContext);

            var appUser = await m_UserManager.GetUserAsync(User);
            Guid userId = Guid.Parse(appUser.Id);
            var journalNotes = m_Database.JournalNotes.Where(j => j.OwnerId == userId).OrderByDescending(j => j.Modified).ToList();
            JournalIndexViewModel viewModel = new JournalIndexViewModel();
            viewModel.PrivateNotes = journalNotes;

            return View(viewModel);
        }

        [Route("journal/{id?}")]
        public async Task<IActionResult> Write(int id = 0)
        {
            if (!m_SignInManager.IsSignedIn(User))
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            CommonCookies.ApplyCommonCookies(HttpContext);

            JournalEntryWrite viewModel = new JournalEntryWrite();
            var appUser = await m_UserManager.GetUserAsync(User);
            Guid userId = Guid.Parse(appUser.Id);
            var journalNote = m_Database.JournalNotes.Where(j => j.Id == id && j.OwnerId == userId).OrderByDescending(j => j.Modified).FirstOrDefault();
            if(journalNote != null)
            {
                viewModel.JournalNote = journalNote;
                viewModel.JournalEntryUpdate.JournalId = journalNote.Id;
                viewModel.JournalEntryUpdate.OwnerId = journalNote.OwnerId;
                viewModel.JournalEntryUpdate.Name = journalNote.Name;
                viewModel.JournalEntryUpdate.Content = journalNote.Content;
            }

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Update(JournalEntryUpdateModel journalEntryUpdate)
        {
            if (!m_SignInManager.IsSignedIn(User))
            {
                return RedirectToAction(nameof(Index));
            }

            Guid ownerId = Guid.Parse(m_UserManager.GetUserId(User));

            JournalNote? journalEntry;
            // Journal update
            if (journalEntryUpdate.JournalId > 0 && journalEntryUpdate.OwnerId == ownerId)
            {
                m_Logger.LogInformation($"Updating journal entry for {ownerId}: {journalEntryUpdate.Name}");
                journalEntry = m_Database.JournalNotes.Where(j => j.Id == journalEntryUpdate.JournalId && j.OwnerId == ownerId).FirstOrDefault();
                journalEntry.Modified = DateTime.Now;
                journalEntry.Content = journalEntryUpdate.Content;
                journalEntry.Name = journalEntryUpdate.Name;
            }
            else
            {
                m_Logger.LogInformation($"Creating journal entry for {ownerId}: {journalEntryUpdate.Name}");
                journalEntry = new JournalNote();
                journalEntry.Created = DateTime.Now;
                journalEntry.Modified = journalEntry.Created;
                journalEntry.OwnerId = ownerId;
                journalEntry.Content = journalEntryUpdate.Content;
                journalEntry.Name = journalEntryUpdate.Name;
                await m_Database.JournalNotes.AddAsync(journalEntry);
            }
            await m_Database.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (!m_SignInManager.IsSignedIn(User))
            {
                return RedirectToAction(nameof(Index));
            }

            Guid ownerId = Guid.Parse(m_UserManager.GetUserId(User));

            JournalNote? journalEntry = m_Database.JournalNotes.Where(j => j.Id == id && j.OwnerId == ownerId).FirstOrDefault();
            if(journalEntry == null)
            {
                return RedirectToAction(nameof(Index));
            }

            m_Database.JournalNotes.Remove(journalEntry);
            await m_Database.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> UploadImage(IFormFile file)
        {
            string uploadsFolder = m_PathService.GetWebRootPath("uploaded_images");

            m_Logger.LogInformation($"Attempting UploadImage {file.FileName} to {uploadsFolder}...");
            var fileName = string.Empty;

            if(file != null && file.Length > 0)
            {
                // TODO: We need to run an antivirus scan on --ANYTHING-- that gets uploaded to the server

                fileName = $"{Guid.NewGuid().ToString()}_{file.FileName}";
                string filePath = Path.Combine(uploadsFolder, fileName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            return Ok(new { FileUrl = fileName });
        }

        [HttpPost]
        public IActionResult DeleteImage(string file)
        {
            string uploadsFolder = m_PathService.GetWebRootPath("uploaded_images");
            string fileItself = Path.GetFileName(file);
            string filePath = Path.Combine(uploadsFolder, fileItself);

            m_Logger.LogInformation($"Attempting delete image {filePath}...");
            if(System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
                m_Logger.LogInformation($"Deleted image {filePath}");
            }

            return Ok();
        }
    }
}

PlanSuite/Views/Journal/Index.cshtml
@using System.Text
@using PlanSuite.Utility
@{
    ViewData["Title"] = "Personal Journal";
}
@model PlanSuite.Models.Temporary.JournalIndexViewModel

<div class="container">
    <div class="text-center">
        <h1 class="display-4">Personal Journal</h1>
        @* Button trigger modal *@

        <a class="btn ps-btn-primary mb-1" asp-controller="Journal" asp-action="Write"><i class="bi bi-journal-plus"></i> New Journal Entry</a>

        <div class="row" id="notesHolder">
            @* Show all journal entries *@
            @if(Model.PrivateNotes.Count > 0)
            {
                foreach(var entry in Model.PrivateNotes)
                {
                    // class="col-sm-6"
                    <div class="card ps-clickable col-sm" id="@entry.Id">
                        <div class="card-body">
                            @{
                                string finalString = UrlUtility.StripHtml(entry.Content);
                                if(finalString.Length > 50)
                                {
                                    finalString = finalString.Remove(50);
                                    finalString += "...";
                                }
                            }

                            <h5 class="card-title">@entry.Name</h5>
                            <p class="card-text">@finalString</p>
                            <span class="ps-link-primary" @*asp-controller="Journal" asp-action="Write" asp-route-id="@entry.Id"*@>Click to read &raquo;</span>
                        </div>
                    </div>
                }
            }
            else
            {
                <p class="mt-3 text-center">You do not have any current active journal entries.</p>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script type="module" src="~/js/journal/index.js" asp-append-version="true"></script>
}

PlanSuite/Views/Journal/Write.cshtml
@using Microsoft.AspNetCore.Http.Extensions
@using PlanSuite.Utility
@{
    ViewData["Title"] = "Write Journal Entry";
    int id = UrlUtility.GetUrlRouteInt(Context.Request, "id");
}
@model PlanSuite.Models.Temporary.JournalEntryWrite

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet"/>

<div class="container">
    @using (Html.BeginForm("Update", "Journal", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.JournalEntryUpdate.JournalId)
        @Html.HiddenFor(model => model.JournalEntryUpdate.OwnerId)
        <div class="modal-body">
            <div class="form-floating mb-3">
                @Html.EditorFor(model => model.JournalEntryUpdate.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.LabelFor(model => model.JournalEntryUpdate.Name, new { htmlAttributes = new { @class = "form-label" } })
                @Html.ValidationMessageFor(model => model.JournalEntryUpdate.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-floating mb-3">
                @Html.TextAreaFor(model => model.JournalEntryUpdate.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JournalEntryUpdate.Content, "", new { @class = "text-danger" })
            </div>
            <div class="modal-footer">
                <a class="btn ps-btn-secondary" asp-controller="Journal" asp-action="Index"><i class="bi bi-x-circle"></i> Close</a>
                <button type="button" class="btn ps-btn-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal"><i class="bi bi-trash"></i> Delete</button>
                <button type="submit" class="btn ps-btn-primary"><i class="bi bi-pencil-square"></i> Save</button>
            </div>
        </div>
    }

    @* Add Column *@
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="confirmDeleteLabel">Delete Journal Note</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you wish to delete this journal? This action is irreversible.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn ps-btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <a class="btn ps-btn-danger" asp-controller="Journal" asp-action="Delete" asp-route-id="@id"><i class="bi bi-trash"></i> Delete</a>
            </div>
        </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script type="module" src="~/js/journal/write.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />
}