PlanSuite/Models/Persistent/Organisation.cs
using PlanSuite.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanSuite.Models.Persistent
{
    [Table("organisations")]
    public class Organisation
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [Column("org_name")]
        public string Name { get; set; }

        [Column("org_desc")]
        public string Description { get; set; }

        [Column("org_tier")]
        public PaymentTier Tier { get; set; }
    }

    [Table("organisation_memberships")]
    public class OrganisationMembership
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [Column("user_id")]
        public Guid UserId { get; set; }

        [Column("organisation_id")]
        public int OrganisationId { get; set; }

        [Column("organisation_role")]
        public ProjectRole Role { get; set; }
    }
}

PlanSuite/Models/Temporary/EditOrganisationViewModel.cs
using PlanSuite.Models.Persistent;

namespace PlanSuite.Models.Temporary
{
    public class EditOrganisationViewModel : BaseViewModel
    {
        public Organisation Organisation { get; set; }
        public EditOrganisationFormModel EditOrganisation = new EditOrganisationFormModel();
        public DeleteOrganisationModel DeleteOrganisation = new DeleteOrganisationModel();
    }

    public class EditOrganisationFormModel
    {
        public int OrganisationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }

    public class DeleteOrganisationModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Guid UserId { get; set; }
    }
}

PlanSuite/Controllers/Api/OrganisationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlanSuite.Data;
using PlanSuite.Enums;
using PlanSuite.Models.Persistent;
using PlanSuite.Models.Temporary;
using PlanSuite.Services;
using Microsoft.EntityFrameworkCore;

namespace PlanSuite.Controllers.Api
{
    [Route("api/[Controller]")]
    [ApiController]
    public class OrganisationController : ControllerBase
    {
        private readonly ApplicationDbContext m_Database;
        private readonly UserManager<ApplicationUser> m_UserManager;
        private readonly ILogger<OrganisationController> m_Logger;

        public OrganisationController(ApplicationDbContext database, UserManager<ApplicationUser> userManager, ILogger<OrganisationController> logger)
        {
            m_Database = database;
            m_UserManager = userManager;
            m_Logger = logger;
        }

        #region GET
        // GET: OrganisationMembers
        [HttpGet("GetOrganisationMembers")]
        public async Task<ActionResult<GetOrganisationMembers>> OrganisationMembers(int orgId)
        {
            GetOrganisationMembers organisationMembers = new GetOrganisationMembers();
            // Check if organisation actually exists.
            var organisation = await m_Database.Organizations.Where(org => org.Id == orgId).FirstOrDefaultAsync();
            if (organisation == null)
            {
                m_Logger.LogError($"Organisation {orgId} does not exist");
                return organisationMembers;
            }

            Console.WriteLine($"Getting organisation members for {orgId}");

            await AddUsersToList(orgId, organisationMembers, ProjectRole.Owner);
            await AddUsersToList(orgId, organisationMembers, ProjectRole.Admin);
            await AddUsersToList(orgId, organisationMembers, ProjectRole.User);

            return organisationMembers;
        }
        #endregion

        private async Task AddUsersToList(int orgId, GetOrganisationMembers organisationMembers, ProjectRole role)
        {
            var members = await m_Database.OrganizationsMembership.Where(owner => owner.OrganisationId == orgId && owner.Role == role).ToListAsync();
            if (members.Count > 0)
            {
                m_Logger.LogInformation($"Get {members.Count} members of role {role} for organisation {orgId}");
                foreach (var member in members)
                {
                    var user = await m_UserManager.FindByIdAsync(member.UserId.ToString());
                    if (user == null)
                    {
                        continue;
                    }
                    switch(role)
                    {
                        case ProjectRole.Admin:
                            if(!organisationMembers.Admins.Contains(user.FullName))
                            {
                                organisationMembers.Admins.Add(user.FullName);
                            }
                            break;
                        case ProjectRole.Owner:
                            if (!organisationMembers.Owners.Contains(user.FullName))
                            {
                                organisationMembers.Owners.Add(user.FullName);
                            }
                            break;
                        default:
                            if (!organisationMembers.Members.Contains(user.FullName))
                            {
                                organisationMembers.Members.Add(user.FullName);
                            }
                            break;
                    }
                    Console.WriteLine($"Add user to list {user.Email} {user.FullName}");
                }
            }
        }
    }
}

PlanSuite/Controllers/OrganisationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlanSuite.Data;
using PlanSuite.Enums;
using PlanSuite.Models.Persistent;
using PlanSuite.Models.Temporary;
using PlanSuite.Services;
using Stripe;

namespace PlanSuite.Controllers
{
    public class OrganisationController : Controller
    {
        private readonly OrganisationService m_OrganisationService;
        private readonly ILogger<OrganisationController> m_Logger;
        private readonly UserManager<ApplicationUser> m_UserManager;
        private readonly ApplicationDbContext m_Database;
        private readonly SignInManager<ApplicationUser> m_SigninManager;
        private readonly AuditService m_AuditService;

        public OrganisationController(OrganisationService organisationService, ILogger<OrganisationController> logger, UserManager<ApplicationUser> userManager, ApplicationDbContext database, SignInManager<ApplicationUser> signInManager, AuditService auditService)
        {
            m_OrganisationService = organisationService;
            m_Logger = logger;
            m_UserManager = userManager;
            m_Database = database;
            m_SigninManager = signInManager;
            m_AuditService = auditService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] CreateOrganisationModel createOrganisation)
        {
            if(!m_SigninManager.IsSignedIn(User))
            {
                return Redirect($"/Identity/Account/Login");
            }

            if (!ModelState.IsValid)
            {
                return Redirect($"/Home/Index?orgStatus={(int)OrganisationErrorCode.ModelStateInvalid}");
            }

            m_Logger.LogInformation($"CreateOrganisation: {createOrganisation.Name} {createOrganisation.Description} {createOrganisation.OwnerId}");
            OrganisationErrorCode errorCode = await m_OrganisationService.OnCreateOrganisation(createOrganisation);

            return Redirect($"/Home/Index?orgStatus={(int)errorCode}");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromForm] DeleteOrganisationModel deleteOrganisation)
        {
            if (!m_SigninManager.IsSignedIn(User))
            {
                return Redirect($"/Identity/Account/Login");
            }

            if (!ModelState.IsValid)
            {
                return Redirect($"/Home/Index?orgStatus={(int)OrganisationErrorCode.ModelStateInvalid}");
            }

            m_Logger.LogInformation($"DeleteOrganisation: {deleteOrganisation.Id} {deleteOrganisation.Name}");
            OrganisationErrorCode errorCode = await m_OrganisationService.OnDeleteOrganisation(deleteOrganisation);

            return Redirect($"/Home/Index?orgStatus={(int)errorCode}");
        }

        [Route("organisations")]
        public async Task<IActionResult> SeeOrganisations()
        {
            if (!m_SigninManager.IsSignedIn(User))
            {
                return Redirect($"/Identity/Account/Login");
            }

            var user = await m_UserManager.GetUserAsync(User);
            if(user == null)
            {
                m_Logger.LogError($"User was null during GetUserAsync");
                return Redirect("/Home/Index");
            }

            SeeOrganisationsModel model = new SeeOrganisationsModel();
            Guid userId = Guid.Parse(user.Id);
            m_Logger.LogInformation($"Grabbing org memberships for user {userId}");

            var organisationMemberships = m_Database.OrganizationsMembership.Where(member => member.UserId == userId).ToList();
            if(organisationMemberships != null && organisationMemberships.Count > 0)
            {
                foreach(var orgMembership in organisationMemberships)
                {
                    if(orgMembership.OrganisationId < 1)
                    {
                        continue;
                    }

                    if (orgMembership.Role < ProjectRole.User)
                    {
                        continue;
                    }

                    var organisation = m_Database.Organizations.Where(org => org.Id == orgMembership.OrganisationId).FirstOrDefault();
                    if (organisation == null)
                    {
                        continue;
                    }

                    if(!model.Organisations.ContainsKey(orgMembership))
                    {
                        m_Logger.LogInformation($"Grabbing org membership for user {userId} for org {organisation.Id}");
                        model.Organisations.Add(orgMembership, organisation);
                    }
                }
            }

            
            return View(model);
        }

        [Route("organisations/{orgId}")]
        public async Task<IActionResult> EditOrganisation(int orgId)
        {
            if (!m_SigninManager.IsSignedIn(User))
            {
                return Redirect($"/Identity/Account/Login");
            }

            var user = await m_UserManager.GetUserAsync(User);
            if (user == null)
            {
                m_Logger.LogError($"User was null during GetUserAsync");
                return Redirect("/Home/Index");
            }

            if(orgId < 1)
            {
                m_Logger.LogError($"OrganisationId was 0 (user: {user.Id})");
                return Redirect("/Home/Index");
            }

            var organisation = m_Database.Organizations.Where(org => org.Id == orgId).FirstOrDefault();
            if(organisation == null)
            {
                m_Logger.LogError($"Organisation was null (user: {user.Id}, OrganisationId: {orgId})");
                return Redirect("/Home/Index");
            }

            var organisationMembership = m_Database.OrganizationsMembership.Where(member => 
                member.OrganisationId == orgId
                && member.UserId == Guid.Parse(user.Id)).FirstOrDefault();
            if(organisationMembership == null)
            {
                m_Logger.LogError($"User {user.Id} was not a member of organisation {orgId}");
                return Redirect("/Home/Index");
            }

            if(organisationMembership.Role < ProjectRole.Owner)
            {
                m_Logger.LogError($"User {user.Id} did not have the correct permissions to edit organisation {orgId}");
                return Redirect("/Home/Index");
            }

            EditOrganisationViewModel model = new EditOrganisationViewModel();
            model.Organisation = organisation;
            await m_AuditService.InsertLogAsync(AuditLogCategory.Organisation, user, AuditLogType.Modified, organisation.Id);

            return View(model);
        }

        [Route("organisations/{orgId}/members/{error?}")]
        public async Task<IActionResult> SeeMembers(int orgId, int error = 0)
        {
            if (!m_SigninManager.IsSignedIn(User))
            {
                return Redirect($"/Identity/Account/Login");
            }

            var user = await m_UserManager.GetUserAsync(User);
            if (user == null)
            {
                m_Logger.LogError($"User was null during GetUserAsync");
                return Redirect("/Home/Index");
            }


            SeeMembersModel model = new SeeMembersModel();
            var organisation = m_Database.Organizations.Where(org => org.Id == orgId).FirstOrDefault();
            if(organisation == null)
            {
                m_Logger.LogError($"Organisation {orgId} does not exist");
                return Redirect("/Organisation/SeeOrganisations");
            }

            model.Organisation = organisation;

            Guid userId = Guid.Parse(user.Id);
            
            var organisationMember = m_Database.OrganizationsMembership.Where(member => 
                member.OrganisationId == orgId &&
                member.UserId == userId &&
                member.Role >= ProjectRole.User).FirstOrDefault();
            if(organisationMember == null)
            {
                m_Logger.LogError($"User {user.Id} is not a member of orgId {orgId} or does not have the correct permissions");
                return Redirect("/Organisation/SeeOrganisations");
            }

            model.OrganisationMembership = organisationMember;

            m_Logger.LogInformation($"Grabbing org membership for orgId {orgId}");

            var organisationMemberships = m_Database.OrganizationsMembership.Where(member => member.OrganisationId == orgId).ToList();
            if (organisationMemberships != null && organisationMemberships.Count > 0)
            {
                foreach (var orgMembership in organisationMemberships)
                {
                    if (orgMembership.Role < ProjectRole.User)
                    {
                        continue;
                    }

                    var orgUser = await m_UserManager.FindByIdAsync(orgMembership.UserId.ToString());

                    switch(orgMembership.Role)
                    {
                        case ProjectRole.Owner:
                            if (!model.Owners.ContainsKey(userId))
                            {
                                model.Owners.Add(userId, orgUser.FullName);
                            }
                            break;
                        case ProjectRole.Admin:
                            if (!model.Admins.ContainsKey(userId))
                            {
                                model.Admins.Add(userId, orgUser.FullName);
                            }
                            break;
                        default:
                            if(!model.Members.ContainsKey(userId))
                            {
                                model.Members.Add(userId, orgUser.FullName);
                            }
                            break;
                    }

PlanSuite/Views/Organisation/EditOrganisation.cshtml
@using Microsoft.AspNetCore.Identity
@using PlanSuite.Enums
@using PlanSuite.Models.Persistent
@using PlanSuite.Services
@model PlanSuite.Models.Temporary.EditOrganisationViewModel
@inject LocalisationService Localisation
@inject UserManager<ApplicationUser> UserManager
@{
    var user = await UserManager.GetUserAsync(User);

    Model.EditOrganisation.OrganisationId = Model.Organisation.Id;
    Model.EditOrganisation.Name = Model.Organisation.Name;
    Model.EditOrganisation.Description = Model.Organisation.Description;

    Model.DeleteOrganisation.Id = Model.Organisation.Id;
    Model.DeleteOrganisation.Name = Model.Organisation.Name;
    Model.DeleteOrganisation.UserId = Guid.Parse(user.Id);

    ViewData["Title"] = Localisation.Get(user, "EDIT_ORGANISATION");
}

<script type="module" src="~/js/organisation/editOrganisation.js" asp-append-version="true"></script>

<div class="container">
    <h3 class="mt-2">@ViewData["Title"]</h3>
    @using (Html.BeginForm("Edit", "Organisation", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.EditOrganisation.OrganisationId)
        <div class="modal-body">
            <div class="form-floating mb-3">
                @Html.EditorFor(model => model.EditOrganisation.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.LabelFor(model => model.EditOrganisation.Name, new { htmlAttributes = new { @class = "form-label" } })
                @Html.ValidationMessageFor(model => model.EditOrganisation.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-floating mb-3">
                @Html.EditorFor(model => model.EditOrganisation.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.LabelFor(model => model.EditOrganisation.Description, new { htmlAttributes = new { @class = "form-label" } })
                @Html.ValidationMessageFor(model => model.EditOrganisation.Description, "", new { @class = "text-danger" })
            </div>
            <div class="modal-footer">
                <button type="button" class="btn ps-btn-danger" data-bs-toggle="modal" data-bs-target="#deleteOrganisationModal"><i class="bi bi-trash"></i> @Localisation.Get(user, "DELETE")</button>
                <button type="submit" class="btn ps-btn-primary"><i class="bi bi-pencil-square"></i> @Localisation.Get(user, "EDIT")</button>
            </div>
        </div>
    }

    @* Create New Project *@
    <div class="modal fade" id="deleteOrganisationModal" tabindex="-1" aria-labelledby="deleteOrganisationLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteOrganisationLabel">@Localisation.Get(user, "DELETE_ORGANISATION")</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                @using (Html.BeginForm("Delete", "Organisation", FormMethod.Post))
                {
                    @Html.HiddenFor(model => model.DeleteOrganisation.Id)
                    @Html.HiddenFor(model => model.DeleteOrganisation.Name)
                    @Html.HiddenFor(model => model.DeleteOrganisation.UserId)
                    <div class="modal-body">
                        <div class="form-floating">
                            @Html.EditorFor(model => model.DeleteOrganisation.Name, new { htmlAttributes = new { @class = "form-control", id = "confirmDeleteOrgName" } })
                            @Html.LabelFor(model => model.DeleteOrganisation.Name, "Enter the organisation name to be able to delete it", new { htmlAttributes = new { @class = "form-label" } })
                            @Html.ValidationMessageFor(model => model.DeleteOrganisation.Name, "", new { @class = "text-danger" })
                            <br>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn ps-btn-secondary" data-bs-dismiss="modal">@Localisation.Get(user, "CLOSE")</button>
                            <button type="submit" class="btn ps-btn-danger" id="deleteButton" disabled>@Localisation.Get(user, "DELETE")</button>
                        </div>
                    </div>
                    
                }
            </div>
        </div>
    </div>
</div>

PlanSuite/Views/Organisation/SeeMembers.cshtml
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Identity
@using PlanSuite.Enums
@using PlanSuite.Models.Persistent
@using PlanSuite.Services
@using PlanSuite.Utility
@inject UserManager<ApplicationUser> UserManager
@inject LocalisationService Localisation
@model PlanSuite.Models.Temporary.SeeMembersModel
@{
    var user = await UserManager.GetUserAsync(User);
    ViewData["Title"] = Localisation.Get(user, "ORGANISATION_MEMBERS");

    Model.AddMember.OrganisationId = Model.Organisation.Id;

    int errorCode = UrlUtility.GetUrlRouteInt(Context.Request, "error");
    int successCode = UrlUtility.GetUrlRouteInt(Context.Request, "success");
}

@*<script type="module" src="~/js/organisation/seeMembers.js" asp-append-version="true"></script>*@

<div class="container">
    <h3>@ViewData["Title"]</h3>
    <h4>@Model.Organisation.Name</h4>

    @if(errorCode > 0)
    {
        string errorMessage = Localisation.Get(user, "UNKNOWN_ERROR");
        switch(errorCode)
        {
            case 1:
                errorMessage = Localisation.Get(user, "CANNOT_FIND_USER");
                break;
            case 2:
                errorMessage = Localisation.Get(user, "NOT_ORG_MEMBER");
                break;
            case 3:
                errorMessage = Localisation.Get(user, "REMOVE_MEMBER_FAIL_ADMIN");
                break;
        }
        <div class="ps-alert ps-alert-error"><i class="bi bi-exclamation-triangle"></i> @errorMessage</div>
    }

    @if(successCode > 0)
    {
        string successMessage = Localisation.Get(user, "ADD_MEMBER_SUCCESS");
        switch(successCode)
        {
            case 1:
                successMessage = Localisation.Get(user, "ADD_MEMBER_SUCCESS");
                break;
            case 2:
                successMessage = Localisation.Get(user, "MAKE_ADMIN_SUCCESS");
                break;
            case 3:
                successMessage = Localisation.Get(user, "REMOVE_MEMBER_SUCCESS");
                break;
        }
        <div class="ps-alert ps-alert-success"><i class="bi bi-check-circle"></i> @successMessage</div>
    }

    <button class="btn ps-btn-primary" data-bs-toggle="modal" data-bs-target="#addMemberModal" id="addMemberBtn"><i class="bi bi-person-plus"></i> Add Member</button>

    <ol class="list-group list-group-numbered mt-3">
        @foreach(var owner in Model.Owners)
        {
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-auto">@owner.Value <span class="badge ps-div-projects rounded-pill">Owner</span></div>
                </div>
            </li>
        }

        @foreach(var admin in Model.Admins)
        {
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-auto">@admin.Value <span class="badge ps-div-projects rounded-pill">Admin</span></div>
                    <a class="btn ps-btn-danger" asp-controller="Organisation" asp-action="RemoveUser" asp-route-userId="@admin.Key"><i class="bi bi-person-dash"></i> Remove</a>
                    @if(Model.OrganisationMembership != null && Model.OrganisationMembership.Role >= ProjectRole.Owner)
                    {
                        <a class="btn ps-btn-secondary" asp-controller="Organisation" asp-action="RemoveAdmin" asp-route-userId="@admin.Key"><i class="bi bi-file-excel"></i> Remove Admin</a>
                    }
                </div>
            </li>
        }
        
        @foreach(var member in Model.Members)
        {
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-auto">@member.Value</div>
                    <a class="btn ps-btn-danger" asp-controller="Organisation" asp-action="RemoveUser" asp-route-userId="@member.Key"><i class="bi bi-person-dash"></i> Remove</a>
                    @if(Model.OrganisationMembership != null && Model.OrganisationMembership.Role >= ProjectRole.Owner)
                    {
                        <a class="btn ps-btn-secondary" asp-controller="Organisation" asp-action="MakeAdmin" asp-route-orgId="@Model.Organisation.Id" asp-route-userId="@member.Key"><i class="bi bi-file-person"></i> Make Admin</a>
                    }
                </div>
            </li>
        }
    </ol>

    <div class="modal fade" id="addMemberModal" tabindex="-1" aria-labelledby="leaveProjectLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="projectMembersLabel">@Localisation.Get(user, "ADD_MEMBER")</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            @using (Html.BeginForm("AddMember", "Organisation", FormMethod.Post))
            {
                @Html.HiddenFor(model => model.AddMember.OrganisationId)
                <div class="modal-body">
                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.AddMember.Username, new { htmlAttributes = new { @class = "form-label" } })
                        @Html.EditorFor(model => model.AddMember.Username, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AddMember.Username, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.AddMember.Email, new { htmlAttributes = new { @class = "form-label" } })
                        @Html.EditorFor(model => model.AddMember.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AddMember.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn ps-btn-primary">@Localisation.Get(user, "ADD_MEMBER")</button>
                        <button type="button" class="btn ps-btn-secondary" data-bs-dismiss="modal">@Localisation.Get(user, "CANCEL")</button>
                    </div> 
                </div>    
            }
        </div>
    </div>
</div>
</div>

PlanSuite/Views/Organisation/SeeOrganisations.cshtml
@using PlanSuite.Enums
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Organisations";
}

<script type="module" src="~/js/organisation/seeOrganisation.js" asp-append-version="true"></script>

<div class="container">
    <h3>@ViewData["Title"]</h3>
    @if(Model.Organisations.Count > 0)
    {
        <ul class="list-group">
            @foreach(var organisation in Model.Organisations)
            {
                string orgRole = "member";
                string editBtn = string.Empty;
                string leaveBtn = $"<a href=\"#\" class=\"btn btn-sm ps-btn-danger\" id=\"onLeaveOrg_{organisation.Value.Id}\"><i class=\"bi bi-arrow-left\"></i> Leave</a>";
                if(organisation.Key.Role == ProjectRole.Admin)
                {
                    // Change role to admin
                    orgRole = "admin";
                }
                else if(organisation.Key.Role == ProjectRole.Owner)
                {
                    // Show edit button for owner, remove leave btn and change role to owner
                    editBtn = $"<a class=\"btn btn-sm ps-btn-secondary\" href=\"/Organisation/EditOrganisation?orgId={organisation.Value.Id}\"><i class=\"bi bi-gear\"></i> Edit</a>";
                    leaveBtn = string.Empty;
                    orgRole = "owner";
                }

                <li class="list-group-item">
                    <a href="#" class="ps-link-primary">@organisation.Value.Name</a> <span class="text-muted">(@orgRole)</span><br>
                    @if(!string.IsNullOrEmpty(organisation.Value.Description))
                    {
                        <p>@organisation.Value.Description</p>
                    }
                    <div class="mt-2"><a class="btn btn-sm ps-btn-primary" asp-controller="Home" asp-action="Index" asp-route-orgId="@organisation.Value.Id"><i class="bi bi-journal-plus"></i> See Projects</a> <a class="btn btn-sm ps-btn-secondary" asp-controller="Organisation" asp-action="SeeMembers" asp-route-orgId="@organisation.Value.Id"><i class="bi bi-people"></i> Members</a> @Html.Raw(editBtn) @Html.Raw(leaveBtn)</div>
                </li>
            }
        </ul>
    }
    else
    {
        <p>You are not in any organisation.</p>
    }

    <div class="modal fade" id="organisationMembersModal" tabindex="-1" aria-labelledby="organisationMembersLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="organisationMembersLabel">Organisation Members</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="d-flex justify-content-center" id="spinner">
                      <div class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                      </div>
                    </div>
                    <ol class="list-group list-group-numbered" id="memberList">
                    </ol>
                    <br>
                    <div class="modal-footer">
                        <button type="button" class="btn ps-btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x-circle"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>